DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT,
    email VARCHAR UNIQUE,
    password VARCHAR,
    firstname VARCHAR,
    lastname VARCHAR,
    salutation VARCHAR,
    role VARCHAR
);

INSERT INTO user (email, password, firstname, lastname, salutation, role) VALUES ('satarovbekzhan@gmail.com', '123', 'Bekzhan', 'Satarov', 'Herr', 'ROLE_ADMIN');
INSERT INTO user (email, password, firstname, lastname, salutation, role) VALUES ('brenda.i.starkey@rhyta.com', '321', 'Brenda', 'Starkey', 'Frau', 'ROLE_MODERATOR');
INSERT INTO user (email, password, firstname, lastname, salutation, role) VALUES ('allenm.m.davis@armyspy.com', '321', 'Allen', 'Davis', 'Herr', 'ROLE_MODERATOR');
INSERT INTO user (email, password, firstname, lastname, salutation, role) VALUES ('wendy.b.herrera@dayrep.com', '213', 'Wendy', 'Herrera', 'Frau', 'ROLE_CUSTOMER');
INSERT INTO user (email, password, firstname, lastname, salutation, role) VALUES ('william.r.jasper@rhyta.com', '213', 'William', 'Jasper', 'Herr', 'ROLE_CUSTOMER');
INSERT INTO user (email, password, firstname, lastname, salutation, role) VALUES ('socorro.c.fries@teleworm.us', '213', 'Socorro', 'Fries', 'Frau', 'ROLE_CUSTOMER');

DROP TABLE IF EXISTS product;
CREATE TABLE product (
    id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT,
    title VARCHAR,
    description TEXT,
    picture VARCHAR
);

INSERT INTO product (title, description, picture) VALUES ('KING’S MUSTARD & SMOKED CHEESE DOUBLE', 'Der King’s Mustard & Smoked Cheese Beef ist nun wirklich alles, was das King’s Selection Herz begehrt. Nicht nur frische Salatgurken, rauchiger Kräuterkäse und zwei 150 Gramm* Beef Patties – sondern gleich zwei neue aromatische Saucen: eine edle Kräuter-Senf-Sauce mit feiner Dillnote und eine süßliche Cumberland-Sauce aus schwarzen Johannisbeeren und Orangenschale.', 'https://www.burgerking.de/tmp/image-thumb__27596__product_detail/tmp-1622025669-17817-de.png');
INSERT INTO product (title, description, picture) VALUES ('KING’S MUSTARD & SMOKED CHEESE BEEF', 'Der King’s Mustard & Smoked Cheese Beef ist nun wirklich alles, was das King’s Selection Herz begehrt. Nicht nur frische Salatgurken, rauchiger Kräuterkäse und ein 150 Gramm* Beef Patty – sondern gleich zwei neue aromatische Saucen: eine edle Kräuter-Senf-Sauce mit feiner Dillnote und eine süßliche Cumberland-Sauce aus schwarzen Johannisbeeren und Orangenschale.', 'https://www.burgerking.de/tmp/image-thumb__27599__product_detail/tmp-1622025675-17816-de.png');
INSERT INTO product (title, description, picture) VALUES ('WHOPPER® WRAP', 'Die Krönung für all unsere Whopper®-Fans: original flame-grilled Beef, frische Tomaten, Zwiebeln und Salat im weichen Tortilla Wrap. Ein Muss für alle, die den Whopper® lieben.', 'https://www.burgerking.de/001_general/products/productimages/wraps/image-thumb__27645__product_detail/WhopperWrap-01.png');
INSERT INTO product (title, description, picture) VALUES ('MOZZARELLA LOVER BEEF', '„Mamma mia“ – so lecker ist der neue Mozzarella Beef. Hol dir jetzt den neuen Burger mit knusprigem Mozzarella-Patty, cremiger Pesto-Sauce und original flame-grilled Beef. Auch als Double erhältlich. Nur bei Burger King.', 'https://www.burgerking.de/tmp/image-thumb__26860__product_detail/tmp-1618933409-17151-de.png');
INSERT INTO product (title, description, picture) VALUES ('FREAKINGDEL', 'Hup Hup Holland Style! Mit dem FreaKingdel holen wir dir die niederländische Spezialität mit saftigen Fleischröllchen aus Beef und Chicken zu dir nach Hause.', 'https://www.burgerking.de/001_general/products/productimages/burger/neue_VI/image-thumb__27120__product_detail/FreaKingdel-01.png');
INSERT INTO product (title, description, picture) VALUES ('STEAKHOUSE JR.', 'Der Steakhouse Jr. – genauso lecker wie sein großer Bruder, nur ein bisschen kleiner. Mit flame-grilled Beef, würziger BBQ Sauce, knusprigem Bacon und herzhaften Röstzwiebeln.', 'https://www.burgerking.de/001_general/products/productimages/burger/neue_VI/image-thumb__26611__product_detail/SteakhouseJr-01.png');
INSERT INTO product (title, description, picture) VALUES ('MOZZARELLA LOVER CHICKEN', '„Mamma mia“ – so lecker ist der neue Mozzarella Chicken. Hol dir jetzt den neuen Burger mit knusprigem Mozzarella-Patty, cremiger Pesto-Sauce und dem leckeren Crunchy Chicken Deluxe Patty. Nur bei Burger King.', 'https://www.burgerking.de/001_general/products/productimages/burger/image-thumb__26853__product_detail/MozzarellaChicken-02.png');
INSERT INTO product (title, description, picture) VALUES ('PLANT-BASED NUGGETS', 'Bei Burger King® gibt es die knusprigen Plant-based* Nuggets von The Vegetarian Butcher – Zero Chicken und trotzdem voller King Nugget-Flavor. Bei The Vegetarian Butcher dreht sich alles darum, das Genusserlebnis von Fleisch nachzubauen – ohne Kompromisse im Geschmack! Glaubst du nicht? Try it to believe it!', 'https://www.burgerking.de/tmp/image-thumb__27880__product_detail/tmp-1623047902-17998-de.png');
INSERT INTO product (title, description, picture) VALUES ('CHEESY ONION FRIES', 'Das perfekte Topping für die King Fries? Genau: Cheddar Sauce und knusprigen Röstzwiebeln! Jetzt bei Burger King®.', 'https://www.burgerking.de/001_general/products/productimages/kingsnacks/image-thumb__26235__product_detail/cheeseonionfries-01.png');
INSERT INTO product (title, description, picture) VALUES ('PLANT-BASED WHOPPER® WRAP', 'Die Krönung für all unsere Whopper®-Fans: leckeres Plant-based* Patty, frische Tomaten, Zwiebeln und Salat im weichen Tortilla Wrap. Ein Muss für alle, die den Whopper® lieben.', 'https://www.burgerking.de/tmp/image-thumb__27773__product_detail/tmp-1622553016-17884-de.png');
INSERT INTO product (title, description, picture) VALUES ('PLANT-BASED NUGGET BURGER', 'Die Idee zum Chicken Nugget Burger war so genial, dass sie uns anfangs niemand geglaubt hat. Die Idee, diesen Burger auch mit Plant-based* Nuggets anzubieten, ist fast noch besser. Knusprige Plant-based* Nuggets von The Vegetarian Butcher mit Hot Curry Sauce und knackigem Salat machen ihn zu einer raffinierten Plant-based-Alternative mit Zero Chicken aber vollem King Nugget Flavour. Nur bei BK!', 'https://www.burgerking.de/tmp/image-thumb__27774__product_detail/tmp-1622553024-17499-de.png');
INSERT INTO product (title, description, picture) VALUES ('MOZZARELLA LOVER PLANT-BASED', '„Mamma mia“ – so lecker ist der neue Mozzarella Plant-based* ohne Fleisch. Hol dir jetzt den neuen Burger mit knusprigem Mozzarella-Patty, cremiger Pesto-Sauce und Plant-based* Patty mit 0% Fleisch – 100% Geschmack. Auch als Double erhältlich. Nur bei Burger King.', 'https://www.burgerking.de/tmp/image-thumb__26856__product_detail/tmp-1618933368-17160-de.png');
INSERT INTO product (title, description, picture) VALUES ('KING SUNDAE SMARTIES®', 'Zum Dahinschmelzen: der neue King Sundae Smarties® mit cremigem Softeis und bunten Smarties®. Sorgt für Sommerfeeling, egal zu welcher Jahreszeit. Auch mit Cornetto® Himbeersauce, Cornetto® Karamellsauce oder Schokosauce erhältlich.', 'https://www.burgerking.de/001_general/products/productimages/sweets/neue_VI/image-thumb__26806__product_detail/KingSundae_Smarties-01.png');
INSERT INTO product (title, description, picture) VALUES ('KING FUSION HAVE IT YOUR WAY®', 'Du hättest am liebsten Oreo®, Smarties® und Cornetto® Himbeersauce zu deinem cremigen Softeis? Kein Problem: Mit dem neuen King Fusion Have It Your Way kannst du dir aus insgesamt 8 verschiedenen Toppings beliebig viele Zutaten aussuchen. Und deinen King Fusion ganz nach deinem Geschmack genießen.', 'https://www.burgerking.de/tmp/image-thumb__27615__product_detail/tmp-1622038173-17314-de.png');
INSERT INTO product (title, description, picture) VALUES ('KING FUSION SMARTIES®', 'So schmeckt der Sommer: cremiges Softeis kombiniert mit herrlicher Schokosauce und farbenfrohen Smarties®. Mit unserem neuen King Fusion Smarties® ist gute Laune vorprogrammiert.', 'https://www.burgerking.de/001_general/products/productimages/sweets/neue_VI/image-thumb__26794__product_detail/KingFusion_Smarties-01.png');
INSERT INTO product (title, description, picture) VALUES ('KING’S MUSTARD & SMOKED CHEESE DOUBLE', 'Der King’s Mustard & Smoked Cheese Beef ist nun wirklich alles, was das King’s Selection Herz begehrt. Nicht nur frische Salatgurken, rauchiger Kräuterkäse und zwei 150 Gramm* Beef Patties – sondern gleich zwei neue aromatische Saucen: eine edle Kräuter-Senf-Sauce mit feiner Dillnote und eine süßliche Cumberland-Sauce aus schwarzen Johannisbeeren und Orangenschale.', 'https://www.burgerking.de/tmp/image-thumb__27596__product_detail/tmp-1622025669-17817-de.png');
INSERT INTO product (title, description, picture) VALUES ('KING’S MUSTARD & SMOKED CHEESE BEEF', 'Der King’s Mustard & Smoked Cheese Beef ist nun wirklich alles, was das King’s Selection Herz begehrt. Nicht nur frische Salatgurken, rauchiger Kräuterkäse und ein 150 Gramm* Beef Patty – sondern gleich zwei neue aromatische Saucen: eine edle Kräuter-Senf-Sauce mit feiner Dillnote und eine süßliche Cumberland-Sauce aus schwarzen Johannisbeeren und Orangenschale.', 'https://www.burgerking.de/tmp/image-thumb__27599__product_detail/tmp-1622025675-17816-de.png');
INSERT INTO product (title, description, picture) VALUES ('KING''S BEEF DOUBLE', 'Der King’s Beef Double mit gleich zwei mal 150 Gramm* flame-grilled Beef, knackig frischem Rucola und knusprigem Bacon ist was für wahre Gourmet-Freunde – serviert im fluffigen Brioche Bun. Aber damit ist es nicht genug – ein außergewöhnlicher Burger verdient auch eine außergewöhnliche Sauce: Unsere Chimichurri-Sauce verleiht unserem King’s Beef die Extraportion Würze. Feine Kräuter wie Oregano und Thymian, veredelt durch Limettensaft, Lorbeer und einen Hauch Knoblauch.', 'https://www.burgerking.de/tmp/image-thumb__27597__product_detail/tmp-1622025671-17853-de.png');
INSERT INTO product (title, description, picture) VALUES ('KING''S BEEF', 'Nur für echte Kings: Der King’s Beef mit 150 Gramm* flame-grilled Beef, knackig frischem Rucola und knusprigem Bacon ist was für wahre Gourmet-Freunde – serviert im fluffigen Brioche Bun. Aber damit ist es nicht genug – ein außergewöhnlicher Burger verdient auch eine außergewöhnliche Sauce: Unsere Chimichurri-Sauce verleiht unserem King’s Beef die Extraportion Würze. Feine Kräuter wie Oregano und Thymian, veredelt durch Limettensaft, Lorbeer und einen Hauch Knoblauch.', 'https://www.burgerking.de/tmp/image-thumb__27598__product_detail/tmp-1622025673-15284-de.png');
INSERT INTO product (title, description, picture) VALUES ('KING’S MUSTARD & SMOKED CHEESE DOUBLE', 'Der King’s Mustard & Smoked Cheese Beef ist nun wirklich alles, was das King’s Selection Herz begehrt. Nicht nur frische Salatgurken, rauchiger Kräuterkäse und zwei 150 Gramm* Beef Patties – sondern gleich zwei neue aromatische Saucen: eine edle Kräuter-Senf-Sauce mit feiner Dillnote und eine süßliche Cumberland-Sauce aus schwarzen Johannisbeeren und Orangenschale.', 'https://www.burgerking.de/tmp/image-thumb__27596__product_detail/tmp-1622025669-17817-de.png');
INSERT INTO product (title, description, picture) VALUES ('KING’S MUSTARD & SMOKED CHEESE BEEF', 'Der King’s Mustard & Smoked Cheese Beef ist nun wirklich alles, was das King’s Selection Herz begehrt. Nicht nur frische Salatgurken, rauchiger Kräuterkäse und ein 150 Gramm* Beef Patty – sondern gleich zwei neue aromatische Saucen: eine edle Kräuter-Senf-Sauce mit feiner Dillnote und eine süßliche Cumberland-Sauce aus schwarzen Johannisbeeren und Orangenschale.', 'https://www.burgerking.de/tmp/image-thumb__27599__product_detail/tmp-1622025675-17816-de.png');
INSERT INTO product (title, description, picture) VALUES ('KING''S BEEF DOUBLE', 'Der King’s Beef Double mit gleich zwei mal 150 Gramm* flame-grilled Beef, knackig frischem Rucola und knusprigem Bacon ist was für wahre Gourmet-Freunde – serviert im fluffigen Brioche Bun. Aber damit ist es nicht genug – ein außergewöhnlicher Burger verdient auch eine außergewöhnliche Sauce: Unsere Chimichurri-Sauce verleiht unserem King’s Beef die Extraportion Würze. Feine Kräuter wie Oregano und Thymian, veredelt durch Limettensaft, Lorbeer und einen Hauch Knoblauch.', 'https://www.burgerking.de/tmp/image-thumb__27597__product_detail/tmp-1622025671-17853-de.png');
INSERT INTO product (title, description, picture) VALUES ('KING''S BEEF', 'Nur für echte Kings: Der King’s Beef mit 150 Gramm* flame-grilled Beef, knackig frischem Rucola und knusprigem Bacon ist was für wahre Gourmet-Freunde – serviert im fluffigen Brioche Bun. Aber damit ist es nicht genug – ein außergewöhnlicher Burger verdient auch eine außergewöhnliche Sauce: Unsere Chimichurri-Sauce verleiht unserem King’s Beef die Extraportion Würze. Feine Kräuter wie Oregano und Thymian, veredelt durch Limettensaft, Lorbeer und einen Hauch Knoblauch.', 'https://www.burgerking.de/tmp/image-thumb__27598__product_detail/tmp-1622025673-15284-de.png');
INSERT INTO product (title, description, picture) VALUES ('WHOPPER® WRAP', 'Die Krönung für all unsere Whopper®-Fans: original flame-grilled Beef, frische Tomaten, Zwiebeln und Salat im weichen Tortilla Wrap. Ein Muss für alle, die den Whopper® lieben.', 'https://www.burgerking.de/001_general/products/productimages/wraps/image-thumb__27645__product_detail/WhopperWrap-01.png');

